create table public.vpvp_books (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying null default ''::character varying,
  author character varying null default ''::character varying,
  description character varying null,
  price smallint null,
  gender character varying null,
  isbn text null,
  year smallint null,
  pages smallint null,
  ratio character varying null,
  editorial character varying null,
  imgurl text not null,
  constraint vpvp_books_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_vpvp_books_created_at on public.vpvp_books using btree (created_at) TABLESPACE pg_default;

create index IF not exists idx_vpvp_books_title_author on public.vpvp_books using btree (title, author) TABLESPACE pg_default;